In [2]:
import pandas as pd
import numpy as np
import json
import psycopg2
import sqlalchemy
from sqlalchemy import create_engine

In [3]:
df = pd.read_json('D:\Final_Project\mongodata\companies.json')

In [5]:
for i in df.items():
    df.append([i[0], i[1]])

C:\Users\aldos\AppData\Local\Temp\ipykernel_2720\1442565683.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df.append([i[0], i[1]])

In [4]:
type(df)

pandas.core.frame.DataFrame

In [46]:
df.dropna()

In [8]:
for i in range(df):
            companies_id = df[i]["_id"]["$oid"]
            name = df[i]["name"]
            permalink = df[i]["permalink"]
            crunchbase_url = df[i]["crunchbase_url"]
            homepage_url = df[i]["homepage_url"]
            blog_url = df[i]["blog_url"]
            blog_feed_url = df[i]["blog_feed_url"]
            twitter_username = df[i]["twitter_username"]
            category_code = df[i]["category_code"]
            number_of_employees = df[i]["number_of_employees"]
            founded_year = df[i]["founded_year"]
            founded_month = df[i]["founded_month"]
            founded_day = df[i]["founded_day"]
            deadpooled_year = df[i]["deadpooled_year"]
            tag_list = df[i]["tag_list"]
            email_address = df[i]["email_address"]
            phone_number = df[i]["phone_number"]
            description = df[i]["description"]
            created_at = str(df[i]["created_at"])
            updated_at = df[i]["updated_at"]
            overview = df[i]["overview"]
            total_money_raised = df[i]["total_money_raised"]
            offices = df[i]["offices"]
            for x in range(len(offices)):
                if(x == 0):
                    offices_description = offices[0]["description"]
                    offices_address1 = offices[0]["address1"]
                    offices_address2 = offices[0]["address2"]
                    offices_zip_code = offices[0]["zip_code"]
                    offices_city = offices[0]["city"]
                    offices_state_code = offices[0]["state_code"]
                    offices_country_code = offices[0]["country_code"]
                    offices_latitude = offices[0]["latitude"]
                    offices_longitude = offices[0]["longitude"]
            data_log = {
                "id" : companies_id,
                "name" : name,
                "permalink" : permalink,
                "crunchbase_url" : crunchbase_url,
                "homepage_url" : homepage_url,
                "blog_url" : blog_url,
                "blog_feed_url" : blog_feed_url,
                "twitter_username" : twitter_username,
                "category_code" : category_code,
                "number_of_employees" : number_of_employees,
                "founded_year" : founded_year,
                "founded_month" : founded_month,
                "founded_day" : founded_day,
                "deadpooled_year" : deadpooled_year,
                "tag_list" : tag_list,
                "email_address" : email_address,
                "phone_number" : phone_number,
                "description" : description,
                "created_at" : created_at,
                "updated_at" : updated_at,
                "overview" : overview,
                "total_money_raised" : total_money_raised,
                "offices_description" : offices_description,
                "offices_address1" : offices_address1,
                "offices_address2" : offices_address2,
                "offices_zipcode" : offices_zip_code,
                "offices_city" : offices_city,
                "offices_state_code" : offices_state_code,
                "offices_country_code" : offices_country_code,
                "offices_latitude" : offices_latitude,
                "offices_longitude" : offices_longitude
            }

            result_log.append(data_log)
        
df = pd.DataFrame.from_dict(result_log)
return df
#companies=pd.json_normalize(json.loads(df1.to_json(orient='records')))

TypeError: 'DataFrame' object cannot be interpreted as an integer

In [1]:
df1.head()

NameError: name 'df1' is not defined

In [64]:
companies['offices'] = companies['offices'].astype(str)

In [59]:
companies['offices', 'description'] = list(map(lambda x: json.dumps(x), companies['offices']))

In [90]:
companies.drop(['partners','created_at.$date.$numberLong'], axis=1, inplace=True)

KeyError: "['partners', 'created_at.$date.$numberLong'] not found in axis"

In [89]:
companies.head()

,name,permalink,crunchbase_url,homepage_url,blog_url,blog_feed_url,twitter_username,category_code,number_of_employees,founded_year,...,tag_list,alias_list,email_address,phone_number,description,created_at,updated_at,overview,total_money_raised,offices
0,Facebook,facebook,http://www.crunchbase.com/company/facebook,http://facebook.com,http://blog.facebook.com,http://blog.facebook.com/atom.php,facebook,social,5299.0,2004.0,...,"facebook, college, students, profiles, network...",,,,Social network,Fri May 25 21:22:15 UTC 2007,1385062855000,<p>Facebook is the world&#8217;s largest socia...,$2.43B,description
1,Facebook,facebook,http://www.crunchbase.com/company/facebook,http://facebook.com,http://blog.facebook.com,http://blog.facebook.com/atom.php,facebook,social,5299.0,2004.0,...,"facebook, college, students, profiles, network...",,,,Social network,Fri May 25 21:22:15 UTC 2007,1385062855000,<p>Facebook is the world&#8217;s largest socia...,$2.43B,address1
2,Facebook,facebook,http://www.crunchbase.com/company/facebook,http://facebook.com,http://blog.facebook.com,http://blog.facebook.com/atom.php,facebook,social,5299.0,2004.0,...,"facebook, college, students, profiles, network...",,,,Social network,Fri May 25 21:22:15 UTC 2007,1385062855000,<p>Facebook is the world&#8217;s largest socia...,$2.43B,address2
3,Facebook,facebook,http://www.crunchbase.com/company/facebook,http://facebook.com,http://blog.facebook.com,http://blog.facebook.com/atom.php,facebook,social,5299.0,2004.0,...,"facebook, college, students, profiles, network...",,,,Social network,Fri May 25 21:22:15 UTC 2007,1385062855000,<p>Facebook is the world&#8217;s largest socia...,$2.43B,zip_code
4,Facebook,facebook,http://www.crunchbase.com/company/facebook,http://facebook.com,http://blog.facebook.com,http://blog.facebook.com/atom.php,facebook,social,5299.0,2004.0,...,"facebook, college, students, profiles, network...",,,,Social network,Fri May 25 21:22:15 UTC 2007,1385062855000,<p>Facebook is the world&#8217;s largest socia...,$2.43B,city

In [91]:
companies.explode('offices')

,name,permalink,crunchbase_url,homepage_url,blog_url,blog_feed_url,twitter_username,category_code,number_of_employees,founded_year,...,tag_list,alias_list,email_address,phone_number,description,created_at,updated_at,overview,total_money_raised,offices
0,Facebook,facebook,http://www.crunchbase.com/company/facebook,http://facebook.com,http://blog.facebook.com,http://blog.facebook.com/atom.php,facebook,social,5299.0,2004.0,...,"facebook, college, students, profiles, network...",,,,Social network,Fri May 25 21:22:15 UTC 2007,1385062855000,<p>Facebook is the world&#8217;s largest socia...,$2.43B,description
1,Facebook,facebook,http://www.crunchbase.com/company/facebook,http://facebook.com,http://blog.facebook.com,http://blog.facebook.com/atom.php,facebook,social,5299.0,2004.0,...,"facebook, college, students, profiles, network...",,,,Social network,Fri May 25 21:22:15 UTC 2007,1385062855000,<p>Facebook is the world&#8217;s largest socia...,$2.43B,address1
2,Facebook,facebook,http://www.crunchbase.com/company/facebook,http://facebook.com,http://blog.facebook.com,http://blog.facebook.com/atom.php,facebook,social,5299.0,2004.0,...,"facebook, college, students, profiles, network...",,,,Social network,Fri May 25 21:22:15 UTC 2007,1385062855000,<p>Facebook is the world&#8217;s largest socia...,$2.43B,address2
3,Facebook,facebook,http://www.crunchbase.com/company/facebook,http://facebook.com,http://blog.facebook.com,http://blog.facebook.com/atom.php,facebook,social,5299.0,2004.0,...,"facebook, college, students, profiles, network...",,,,Social network,Fri May 25 21:22:15 UTC 2007,1385062855000,<p>Facebook is the world&#8217;s largest socia...,$2.43B,zip_code
4,Facebook,facebook,http://www.crunchbase.com/company/facebook,http://facebook.com,http://blog.facebook.com,http://blog.facebook.com/atom.php,facebook,social,5299.0,2004.0,...,"facebook, college, students, profiles, network...",,,,Social network,Fri May 25 21:22:15 UTC 2007,1385062855000,<p>Facebook is the world&#8217;s largest socia...,$2.43B,city
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77495,Intergy,intergy,http://www.crunchbase.com/company/intergy,http://www.intergycorp.com,,,,software,NaN,2003.0,...,,,info@intergycorp.com,925-556-2600,,Sun Jul 12 08:36:38 UTC 2009,1247388144000,<p>Energy is a critical necessity to the moder...,$0,city
77496,Intergy,intergy,http://www.crunchbase.com/company/intergy,http://www.intergycorp.com,,,,software,NaN,2003.0,...,,,info@intergycorp.com,925-556-2600,,Sun Jul 12 08:36:38 UTC 2009,1247388144000,<p>Energy is a critical necessity to the moder...,$0,state_code
77497,Intergy,intergy,http://www.crunchbase.com/company/intergy,http://www.intergycorp.com,,,,software,NaN,2003.0,...,,,info@intergycorp.com,925-556-2600,,Sun Jul 12 08:36:38 UTC 2009,1247388144000,<p>Energy is a critical necessity to the moder...,$0,country_code
77498,Intergy,intergy,http://www.crunchbase.com/company/intergy,http://www.intergycorp.com,,,,software,NaN,2003.0,...,,,info@intergycorp.com,925-556-2600,,Sun Jul 12 08:36:38 UTC 2009,1247388144000,<p>Energy is a critical necessity to the moder...,$0,latitude
77499,Intergy,intergy,http://www.crunchbase.com/company/intergy,http://www.intergycorp.com,,,,software,NaN,2003.0,...,,,info@intergycorp.com,925-556-2600,,Sun Jul 12 08:36:38 UTC 2009,1247388144000,<p>Energy is a critical necessity to the moder...,$0,longitude

In [92]:
engine = create_engine('postgresql+psycopg2://postgres:admin@localhost:5432/postgres')
companies.to_sql('companies', engine, if_exists='replace')

500